language: node_js
install:
- yarn install
node_js:
- node
deploy:
  app: pikojs
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: cmmElq9N5B4GWIu9eWHlb43bkPnI1sA5z4eefpBilrDPTfmaPWL076mJkqpGb692+RpcJiE/YtqnD599ox3dGd7uPdpDD00sBUW17UXPnybsCxeSUu/pIznFnmBXIWNVM+pjeXtpNKwsDM1/JTA7mvglTslw/Z9Rn0Kia3PmzNW1osw5qsR1BUiYbEzv9ATJ3z9KBKwID4Z8NdenUv1NDSILXwbz0nYgKnxx91BmpMK9GLdGMZMvLXFb9jVZrySeEc9/rdyP2n4rE4VShm5w1cenvJ+yTnKJpDqDtWxVhubixR2Zmtnc6D3ytGxnXdNXntzNmkJaRS4LPCSFh1OosE3UL7T4tmQ3UFtYIPpMqRcYCgo2/2RwOr5tcPDvWmtaitfZrwqsegvq6g1zrRKn5jKXx6fIEjsuT6X8USbpsWLrylpuIUGj1+JQRuytpscRT3Hcwm1R91Lk1g0LkglRZnn9OLaUgLVxmjoQ2Jrs79vv+B1+Jl5H7yeYQdgy0Bo8xj0jDMPGy5kCSCmDTkfFOwTVKX3ioidcBB94Nu1QuXU9oGSpyhHNHJzaWlfz07fr0J2PuA3o2KOkJ3ZoA4Xn4dvW7o+Xbz/1EWVbix7Pj9wYefdrhCstf5dsfqgWl+EQCkZTFu7vQJSyyzungREEL5Y7CcoNUrSm5hSpN/hcCHQ=
